### PR TITLE
page_store: always reclaimate empty page file

### LINKED ISSUE #213: Space reclamation needs to be enhanced
Currently flush directly marks page files with no active pages as deleteable, which is problematic because dealloc pages are also recorded in page files. 

The conditions need to be added to fix the issue: #212. However, this will cause space reclamation to not work properly, because space reclamation simply rewrites dealloc pages, which does not facilitate the space reclamation process.

### PR DESCRIPTION
**Pull request by w41ter**
This PR closes #213.

### CODE REVIEW

File: src/page_store/jobs/gc.rs [hunk 1]
```diff
@@ -71,23 +71,70 @@ where
     }
 
     async fn gc(&mut self, version: &Arc<Version>) {
+        // Reclaimate deleted files in `cleaned_files`.
```
Comment (huachaohuang) [inline src/page_store/jobs/gc.rs:74]:
```suggestion
        // Reclaim deleted files in `cleaned_files`.
```

I think "reclaimate" is not a word :)
